### PR TITLE
Add support for 305.0.0.0.92

### PR DESCRIPTION
**Pull request by down-bad**

### CODE REVIEW

**Comment by down-bad** [comment]
I think we should also support at least the latest beta and stable as well. Thoughts? Ok you just merged it while i was typing

**Comment by ReSo7200** [comment]
You can contribute as much as you want.

However note that the users once they use our module and enable is employee options, they would be able to update to whatever version they want...

**Comment by ReSo7200** [comment]
The thing which makes us update the supported versions, is that sometimes some of the versions becomes out dated that it won't let you use instagram unless you update it...

**Comment by down-bad** [comment]
I thought of having latest stable and beta support for people who don't wanna use alpha, but maybe it's not that important.

**Comment by ReSo7200** [comment]
Maybe you are right.

Last time I checked (2xx versions) stable were having some type of obfuscation, but if (3xx versions) stables were ez to do I would support ur call

**Pull request merged**
